version: 2
updates:
  # Enable Dependabot updates for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates weekly

  # Enable Dependabot updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates weekly

  # Enable Dependabot updates for Nix Flakes
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates weekly
